---
title: "Econ 366, Data Assignment 1"
author: "Andrew Leach"
editor: source
---



```{r chunks,echo=T,output=F, warning=FALSE,include=FALSE}
knitr::opts_chunk$set(message=F,
                      warning=F,
                      include=T)
# include all your code, but not warnings or loading messages in your output
```


```{r packages-data,echo=T,output=F, warning=FALSE,include=T}
#load your packages
library(kableExtra)
library(readxl)
library(janitor)
library(tidyverse)
library(lubridate)
library(scales)
library(viridis)
```


## Downloading the data

```{r read data}
#your code here

```

## Deliverable 1 

```{r deliverable_1}
#your code here


```

## Deliverable 2 


```{r, out.width="95%",dpi=300,fig.align="center"}
#your code here (I set it up to make a nice image for you)

#this is just to show you that the graph output will work
ggplot(mtcars, aes(x=hp, y=mpg, color=as.factor(cyl))) +
    geom_point(size=3)+
    scale_color_brewer("Cylinders")
    


```

## Deliverable 3 


```{r, out.width="95%",dpi=300,fig.align="center"}
#your code here (I set it up to make a nice image for you)


```



## Deliverable 4 

You can just type here. It will format it nicely enough for these purposes. Be careful with plagiarism: I want your own words, and you should not need to use more than the CER report as your source document.


## Deliverable 5 (Your graph to support deliverable 4)

```{r, out.width="95%",dpi=300,fig.align="center"}
#your code here (I set it up to make a nice image for you)


```




